### ISSUE TITLE
通过css设置等宽高图片box

### ISSUE THREAD

**Issue by likun7981** [likun7981/blog#4]
有时候图片的宽高不相等的时候，需要设置宽高相等的box来包裹，达到自适应的效果。这个情况的解决方案有
* 使用js控制。缺点：会很麻烦，而且使用js来改变样式会导致后期维护不方便；优点：兼容浏览器效果很好
* 使用样式控制。缺点：对于不支持伪元素的浏览器不适用；优点：使用样式表控制后期很容易维护，代码如下

Html:
```html
    <div class='container'>
        <img src="...">
    </div>
```
CSS:
```css
   .container{
    position: relative;
    width: 50%;        /* desired width */
   }
   .container:before{
     content: "";
     display: block;
     padding-top: 100%;     /* initial ratio of 1:1*/
   }
  .box img {
    position:  absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
   }
```
